version: 2.1
executors:
  docker-executor:
    docker:
      - image:  node
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    executor: docker-executor
    steps:
     - attach_workspace:
        at: ./
      - checkout
      - run: npm run test:unit
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires: 
            - build
