version: 2.1
executors:
  docker-executor:
    docker:
      - image:  node
  docker-builder:    
    docker:
      - image:  python:2-alpine
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:unit
  deploy:
    executor: docker-builder
    environment:
    steps:
      - attach_workspace:
          at: ./
      - run: pip install awscli
      - run: export AWS_ACCESS_KEY_ID=$ACCESS_KEY_AWS
      - run: export AWS_SECRET_ACCESS_KEY=$SECRET_KEY_AWS
      - run: export AWS_DEFAULT_REGION=sa-east-1
      - run: aws s3 ls
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop
              
